---
title: "Parkinson's Project"
author: "Rachel Weber"
date: "November 8, 2017"
output: pdf_document
---

Question 1: After accounting for exercise group differences, do people who have been diagnosed for longer, see a smaller benefit in exercise intervention?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/weberra/Downloads")
library(ggplot2)

park <- read.csv(file="Parkinsons.csv", sep=",")
```

```{r}
# generate improvement columns
park$sixdif <- park$SixMn_Wk16-park$SixMn_Wk0 # time taken week 16-time taken week 0
park$secondsdif <- park$FiveM_Tm16-park$FiveM_Tm0 #time take week 16-time taken week 0

hist(park$sixdif)
summary(park$sixdif) # mean -4.5, median -5.3

hist(park$secondsdif)
summary(park$secondsdif) # mean .018, median -.02

# t tests for any difference between weeks 0 and 16
t.test(park$FiveM_Tm0, park$FiveM_Tm16) # not significant
t.test(park$SixMn_Wk0, park$SixMn_Wk16) # not significant

# t tests controlling for group
t.test(park$FiveM_Tm0[park$Group == "6"], park$FiveM_Tm16[park$Group == "6"]) # not significant
t.test(park$SixMn_Wk0[park$Group == "6"], park$SixMn_Wk16[park$Group == "6"]) # not significant
t.test(park$FiveM_Tm0[park$Group == "5"], park$FiveM_Tm16[park$Group == "5"]) # not significant
t.test(park$SixMn_Wk0[park$Group == "5"], park$SixMn_Wk16[park$Group == "5"]) # not significant
t.test(park$FiveM_Tm0[park$Group == "4"], park$FiveM_Tm16[park$Group == "4"]) # not significant
t.test(park$SixMn_Wk0[park$Group == "4"], park$SixMn_Wk16[park$Group == "4"]) # not significant

# since there isn't a significant difference, is measuring improvement worth while?
# additionally, is the intervention even working?
```



```{r}
park$Group <- as.factor(park$Group)

# years since diagnosis predicting improvement in mobility/coordination
distance_improve <- ggplot(park, aes(x=YearsDx, y=sixdif, group=Group, col=Group)) + geom_point()
sec_improve <- ggplot(park, aes(x=YearsDx, y=secondsdif, group=Group, col=Group)) + geom_point()

# UPDRS score at week 1 predicting improvement in mobility/coordination
distance_improve <- ggplot(park, aes(x=UPDRS0, y=sixdif, group=Group, col=Group)) + geom_point()
sec_improve <- ggplot(park, aes(x=UPDRS0, y=secondsdif, group=Group, col=Group)) + geom_point()

```

```{r}
# test for normality of distributions
hist(park$sixdif)
hist(park$secondsdif)
res <- cor.test(park$YearsDx, park$sixdif, method = "")
```



```{r}
# crude models containing only treatment group
lm_crude_six <- lm(park$sixdif ~ park$Group) # group 6 significant
lm_crude_sec <- lm(park$secondsdif ~ park$Group) # not significant

ggplotRegression(lm(sixdif ~ Group, data = park))
# unimpressive significance may mean I don't have to adjust for it in the model

#years since diagnosis
lm_sixmeters <- lm(park$sixdif ~ park$YearsDx + park$Group)
lm_seconds <- lm(park$secondsdif ~ park$YearsDx + park$Group)

# UPDRS score
lm_sixmeters_score <- lm(park$sixdif ~ park$UPDRS0 + park$Group) # score not significant
lm_seconds_score <- lm(park$secondsdif ~ park$UPDRS0 + park$Group) # nothing significant

# since groups aren't significant in predicting change, run models without them
seconds_score <- lm(park$secondsdif ~ park$UPDRS0) # not significant
six_score <- lm(park$sixdif ~ park$UPDRS0) # not significant
seconds_years <- lm(park$secondsdif ~ park$YearsDx) # not significant
six_years <- lm(park$secondsdif ~ park$YearsDx) # not significant
```


```{r}

```

```{r}

```

